version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn start:dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    working_dir: /app
    user: 1000:1000
